#!/data/data/com.termux/files/usr/bin/bash

############################################
#        Project : Nitro-allinone           #
#          author : Nitro                 #
#       #
############################################

clear
echo 
echo "
          █▀▄▀█ █▀▀ █▀▀ ▄▀█ █▀█ ▄▀█ █▀▀ █▄▀ ▄▀█ █▀▀ █▀▀
          █ ▀ █ ██▄ █▄█ █▀█ █▀▀ █▀█ █▄▄ █ █ █▀█ █▄█ ██▄
	                                                V 1.0" | lolcat	      
echo "                   >>> created by:-Nitro " |lolcat
echo "              >>> Keep Supporting:-Nitro Hacker " |lolcat
echo " "
echo -e "\e[92m=======================================================================\e[m "
echo -e "\e[32m[\e[33m01\e[32m]\e[96m Termux-package \e[m                \e[32m[\e[33m11\e[32m]\e[96m Ngrok \e[m "                  
echo -e "\e[92m=======================================================================\e[m "
echo " "
read -p $'\e[34m[*]\e[33m Enter Your Choice : \e[0m' n
echo
if [[ $n == 1 || $n == 01 ]]; then

	     DIR="$HOME/Termux-Package"
	        if [ -d "$DIR" ]; then
	     cd $HOME
	     cd Termux-Package
	     python termux-package.py
	     cd $HOME

	     else

	      echo -e "\e[34m[*] Installing Termux-package \e[m "
	      sleep 5
	      clear
	      cd $HOME
	      apt install git 
              apt install python 
              git clone https://github.com/Hackertrackersj/Termux-Package
              cd Termux-package
              ls
              chmod +x *
              ls
              python2 termux-package.py
              cd $HOME
		 fi
    echo -en "\e[92m Do you wish to see a practical video on it (y/n)? \e[m "

read answer
 
 	 if [ "$answer" != "${answer#[Yy]}" ] ;then
       
       am start -a android.intent.action.VIEW -d https://youtu.be/5uFVhDACups >> /dev/null 2>&1
	else
		echo
		fi
  
		  
else
	      echo -e "\e[33m[\e[31m!\e[33m]\e[91mInvalid option \e[m" 
fi	  
  echo " "
  exit
